# Builds a Docker image and publishes it to the Forgejo container registry

name: Publish Docker image

on:
  push:
    # Publish semver tags as releases.
    tags: ["v*.*.*"]

env:
  REGISTRY: git.average.name
  # forge.repository as <account>/<repo> (See https://forgejo.org/docs/latest/user/actions/reference/#forge)
  IMAGE_NAME: ${{ forge.repository }}

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        # actions/checkout@v6.0.2
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Log in to container registry
        # docker/login-action@v3.6.0
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ forge.actor }}
          password: ${{ secrets.PACKAGES_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        # docker/metadata-action@v5.10.0
        uses: docker/metadata-action@c299e40c65443455700f0fdfc63efafe5b349051
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Build and push Docker image
        # docker/build-push-action@v6.18.0
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
